# See https://github.com/pymor/pymor/blob/main/.github/workflows/linter.yml

name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: pipx install poetry black flake8 pylint
    - uses: actions/setup-python@v6
      with:
        python-version: ">=3.11"
        cache: poetry
    - run: poetry install
    - name: Prepare artifacts directory
      run: |
        mkdir -p ./linter_output
        echo ${{ github.event.number }} > ./linter_output/pr_number
        echo ${{ github.event.pull_request.head.sha }} > ./linter_output/head_sha
    - name: Lint with black
      run: black . --check 2>&1 >/dev/null | tee ./linter_output/black.out
    - name: Lint with flake8
      run: flake8 | tee ./linter_output/flake8.out
    - name: Lint with pylint
      run: pylint ietf_reviewtool tests --output-format=json | tee ./linter_output/pylint.out

    - uses: actions/upload-artifact@v4
      with:
        name: linter_output
        path: linter_output
