name: Lint

on: [pull_request]

env:
  LINTLY_API_KEY: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markupsafe==2.0.1 black==20.8b1 # this is temporary
        pip install flake8 pylint lintly poetry
        poetry export -o requirements.txt
        pip install -r requirements.txt
    - name: Lint with black
      run: black . --check | lintly --use-checks --format=black
    - name: Lint with flake8
      run: flake8 | lintly --use-checks --format=flake8
    - name: Lint with pylint
      run: pylint ietf_reviewtool tests --output-format=json | lintly --use-checks --format=pylint-json
