# See https://github.com/pymor/pymor/blob/main/.github/workflows/linter.yml

name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-22.04 # TODO: Unpin
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint poetry
        poetry self add poetry-plugin-export
        poetry export -o requirements.txt
        pip install -r requirements.txt
    - name: Prepare artifacts directory
      run: |
        mkdir -p ./linter_output
        echo ${{ github.event.number }} > ./linter_output/pr_number
        echo ${{ github.event.pull_request.head.sha }} > ./linter_output/head_sha
    - name: Lint with black
      run: black . --check 2>&1 >/dev/null | tee ./linter_output/black.out
    - name: Lint with flake8
      run: flake8 | tee ./linter_output/flake8.out
    - name: Lint with pylint
      run: pylint ietf_reviewtool tests --output-format=json | tee ./linter_output/pylint.out

    - uses: actions/upload-artifact@v4
      with:
        name: linter_output
        path: linter_output
