# See https://github.com/pymor/pymor/blob/main/.github/workflows/process_linter_results.yml

name: Process linter results

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' }}
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v2
        id: download
        with:
          name: "linter_output"
          path: "${{github.workspace}}/linter_output.zip"
      - run: unzip ${{steps.download.outputs.download-path}}
      - name: Set up Python
        uses: actions/setup-python@v3
      # pinned to lintly 0.5.0 due to https://github.com/grantmcconnaughey/Lintly/issues/41
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lintly==0.5.0 markupsafe==2.0.1
      - name: 'Comment on PR'
        run: |
          cat ./flake8.out | lintly --format=flake8 \
            --use-checks \
            --fail-on new \
            --pr="$(cat ./pr_number)" \
            --exit-zero \
            --no-post-status \
            --commit-sha="$(cat ./head_sha)"
          cat ./black.out | lintly --format=black \
            --use-checks \
            --fail-on new \
            --pr="$(cat ./pr_number)" \
            --exit-zero \
            --no-post-status \
            --commit-sha="$(cat ./head_sha)"
          cat ./pylint.out | lintly --format=pylint-json \
            --use-checks \
            --fail-on new \
            --pr="$(cat ./pr_number)" \
            --exit-zero \
            --no-post-status \
            --commit-sha="$(cat ./head_sha)"
        env:
          LINTLY_API_KEY: ${{ secrets.GITHUB_TOKEN }}
