# See https://github.com/pymor/pymor/blob/main/.github/workflows/linter.yml

name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v6
    - run: uv sync --group dev --group types
    - name: Prepare artifacts directory
      env:
        PR_NUMBER: ${{ github.event.number }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        mkdir -p ./linter_output
        echo "$PR_NUMBER" > ./linter_output/pr_number
        echo "$HEAD_SHA" > ./linter_output/head_sha
    - name: Lint with pylint
      run: uv run pylint ietf_reviewtool tests --output-format=json | tee ./linter_output/pylint.out
    - name: Check with ruff
      run: uv run ruff check ietf_reviewtool tests
    - name: Format check with ruff
      run: uv run ruff format --check ietf_reviewtool tests
    - name: Type check with mypy
      run: uv run mypy ietf_reviewtool

    - uses: actions/upload-artifact@v7
      with:
        name: linter_output
        path: linter_output
