name: Python package

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v7
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}
    - run: uv sync
    # - name: Test with pytest
    #   run: |
    #     uv run pytest
